(() => {
  const page = document.querySelector('[data-legal-page]');
  const content = document.querySelector('[data-legal-content]');
  if (!page || !content) return;
  const notice = '<div class="legal-notice"><strong>Important:</strong> Predict-A-Trade provides informational and analytical content only. Trading financial instruments involves substantial risk, and no signal or analysis guarantees an outcome.</div>';
  const pages = {
    'probability-signal-warning': ['PROBABILITY SIGNAL WARNING', [['Probability is not certainty', '<p>A probability signal is an analytical assessment at a point in time. It is not a guaranteed prediction, guaranteed trade outcome, or promise of profit.</p><p><strong>Probability ≠ Certainty. Signal ≠ Guaranteed Outcome. Confidence ≠ Certainty. Historical Result ≠ Future Result. Backtest ≠ Live Performance. Analysis ≠ Financial Advice.</strong></p>'], ['Limitations', '<p>Volatility, liquidity, spreads, slippage, broker conditions, news, data quality, latency, regime changes, and unexpected events can affect outcomes. An analytical system can be wrong.</p>']]],
    'no-guarantee': ['NO GUARANTEE NOTICE', [['No guaranteed results', '<p>Predict-A-Trade does not guarantee profits, trading success, signal accuracy, prediction accuracy, market direction, execution results, or any particular financial outcome.</p><p>No probability, score, confidence level, or signal should be interpreted as certainty or a guarantee.</p>']]],
    'financial-notice': ['FINANCIAL NOTICE', [['What the service provides', '<p>Predict-A-Trade focuses on XAUUSD market intelligence, combining market structure, technical analysis, liquidity, volatility, multi-timeframe context, and computational analysis.</p>'], ['What it does not provide', '<p>Outputs are not investment management, brokerage, execution, personalized financial advice, or a promise of a financial outcome.</p>'], ['User responsibility', '<p>Users remain solely responsible for their trading and investment decisions. Consider your circumstances and risk tolerance and seek independent professional advice where appropriate.</p>']]],
    'trading-risk-disclosure': ['TRADING RISK DISCLOSURE', [['Material risks', '<p>XAUUSD can be volatile. Leverage, margin, liquidation, spread, slippage, liquidity, broker, counterparty, technology, data-feed, execution-latency, news, geopolitical, and market-gap risks may affect results.</p>'], ['Risk statement', '<p>Trading financial instruments can result in substantial losses, including loss of capital. Prices and execution conditions can differ between providers and brokers.</p>']]],
    'not-financial-advice': ['NOT FINANCIAL ADVICE', [['Scope', '<p>Signals and market commentary are informational and analytical, not individualized financial advice. They may not consider a user’s circumstances, objectives, or risk tolerance. Users make their own decisions.</p>']]],
    'refund-cancellation': ['REFUND, CANCELLATION & PAYMENT POLICY', [['Current website scope', '<p>This static public website contains no pricing, checkout, subscription, or payment flow. No fee, renewal, refund, or cancellation term is represented here as a live offer.</p>'], ['Future paid services', '<p>If paid services are introduced, checkout must clearly disclose the product, price, billing, renewal, cancellation, failed payments, access termination, taxes, processors, and refund conditions before purchase. Fees should be described as non-refundable only where legally appropriate and subject to applicable law.</p>']]],
    'regulation': ['REGULATION & REGULATORY TRANSPARENCY', [['Verified position', '<p>This package contains no verified evidence of a license, registration, authorization, regulator, certification, brokerage status, investment-adviser status, or asset-management permission. No such claim should be inferred.</p>'], ['Jurisdiction', '<p>Financial-market activities may be regulated differently by location. Users are responsible for determining whether use is lawful in their jurisdiction.</p>']]],
    'user-terms': ['USER TERMS', [['Acceptable use', '<p>Use the website lawfully. Do not disrupt services, scrape or redistribute protected content, impersonate Predict-A-Trade, request credentials from others, or reverse engineer the bundle.</p>'], ['Outputs and availability', '<p>Signals are analytical decision-support information, not guaranteed outcomes. External services have their own operators and terms; availability is not guaranteed.</p>']]],
    'terms-and-policies': ['TERMS & POLICIES', [['Use and intellectual property', '<p>Use the site lawfully. Website text, software, branding, and media belong to Predict-A-Trade or licensors unless stated otherwise. Do not copy, scrape, redistribute, or reverse engineer them without permission.</p>'], ['Risk and related policies', '<p>Market information can be delayed, incomplete, or incorrect. Predict-A-Trade does not guarantee profits, accuracy, execution, or any financial result. Review the <a href="/legal/user-terms/">User Terms</a>, <a href="/legal/financial-notice/">Financial Notice</a>, <a href="/legal/trading-risk-disclosure/">Trading Risk</a>, <a href="/legal/privacy-policy/">Privacy Policy</a>, and <a href="/legal/cookie-policy/">Cookie Policy</a>.</p>']]],
    'fraud-warning': ['FRAUD WARNING', [['Warning signs', '<p>Be cautious of fake websites, impersonators, fake support accounts, guaranteed-profit offers, fake agents, fake brokers, and unexpected payment requests.</p>'], ['Never disclose', '<p>Do not share passwords, OTPs, private keys, recovery phrases, API secrets, authentication tokens, banking credentials, or remote-desktop access with unauthorized persons.</p>'], ['Verify channels', '<p>Check the HTTPS domain and independently verify communications. This package does not publish a list of official social accounts.</p>']]],
    'complaints': ['COMPLAINTS PROCEDURE', [['Submit a complaint', '<p>Email <a href="mailto:predictatrade@gmail.com">predictatrade@gmail.com</a> with “Complaint” in the subject. Include your name, contact details, relevant date or service, description, and desired outcome. Never include passwords or payment credentials.</p>'], ['Review', '<p>We will acknowledge receipt where possible, review available information, request clarification when needed, and provide a response. Statutory deadlines and escalation authorities are not asserted without verified jurisdictional information.</p>']]],
    'privacy-policy': ['PRIVACY POLICY', [['Information received', '<p>The site does not require an account or collect trading data. Email messages contain the information you choose to send and are handled by mailbox and hosting providers.</p>'], ['Technical data and third parties', '<p>Hosting may process request metadata in ordinary logs. The homepage requests fonts from Google Fonts and links to external websites. This package contains no analytics, advertising, marketing pixels, or embedded social widgets.</p>'], ['Questions', '<p>For privacy questions, email <a href="mailto:predictatrade@gmail.com">predictatrade@gmail.com</a>.</p>']]],
    'cookie-policy': ['COOKIE POLICY', [['Technologies detected', '<p>The website uses browser local storage for preference choices. It does not currently load analytics, advertising, marketing pixels, or chat widgets. Google Fonts is a third-party font request and may have its own policy.</p>'], ['Choices', '<p>Use <a href="/legal/cookie-settings/">Cookie Settings</a> to accept or reject optional categories and change them later. No optional technology is loaded by this static package.</p>']]],
    'data-disclaimer': ['DATA DISCLAIMER', [['Data limitations', '<p>Prices may be delayed, differ between providers or brokers, contain errors, or be interrupted. Execution prices, spreads, and liquidity can differ from displayed information.</p>'], ['No live claim', '<p>This public marketing package does not itself display a live XAUUSD feed or execute trades.</p>']]],
    'affiliate-disclosure': ['AFFILIATE DISCLOSURE', [['Current position', '<p>No affiliate relationship or commission arrangement is identified in this static website package. No affiliate claim should be inferred.</p>'], ['Future changes', '<p>Any future paid referral or affiliate relationship should be disclosed clearly before it affects a recommendation or user decision.</p>']]],
    'intellectual-property': ['INTELLECTUAL PROPERTY NOTICE', [['Ownership', '<p>Predict-A-Trade branding, text, software bundle, and media are protected by applicable intellectual-property rights and may belong to Predict-A-Trade or licensors.</p>'], ['Permitted use', '<p>Visitors may view the public website for its intended purpose. Reproduction, commercial reuse, scraping, or reverse engineering requires permission.</p>']]],
    'cookie-settings': ['COOKIE SETTINGS', [['Settings', '<form class="cookie-form" data-cookie-form><fieldset><legend class="legal-kicker">Categories</legend><label class="cookie-option"><input type="checkbox" checked disabled><span><strong>Necessary</strong><p>Required for basic delivery and always enabled.</p></span></label><label class="cookie-option"><input type="checkbox" name="preferences"><span><strong>Preferences</strong><p>Optional local preference storage. No optional feature currently depends on it.</p></span></label><label class="cookie-option"><input type="checkbox" name="analytics"><span><strong>Analytics</strong><p>No analytics provider is currently loaded.</p></span></label><label class="cookie-option"><input type="checkbox" name="marketing"><span><strong>Marketing</strong><p>No marketing technology is currently loaded.</p></span></label><div class="cookie-actions"><button type="submit">Save preferences</button><a class="secondary" href="/legal/cookie-policy/">Read Cookie Policy</a></div><p class="cookie-status" data-cookie-status role="status" aria-live="polite"></p></fieldset></form>']]]
  };
  const entry = pages[page.dataset.legalPage];
  if (!entry) return;
  document.title = `Predict-A-Trade ${entry[0]}`;
  content.innerHTML = notice + entry[1].map(([heading, body]) => `<section><h2>${heading}</h2>${body}</section>`).join('');
})();
